### ISSUE TITLE
SD3 Support?

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [Scorpinaus/ComfyUI-DiffusersLoader#3]
SD3 Support?

**Comment by Scorpinaus** [comment]
Hi Alex, I will be implementing SD3 support. It will take a few days, but once its working I will update the repo

**Comment by a-l-e-x-d-s-9** [comment]
Thank you very much.
Diffusers haven't released a script to convert diffusers format of DiT to the original format, that I reported: https://github.com/huggingface/diffusers/issues/8588
So it's currently not possible to load checkpoints from diffusers training into ComfyUI for SD3.

**Comment by Scorpinaus** [comment]
Hi Alex, initial SD3 support is up! Tested it with the SD3 diffusers and it works! Please update the latest version and lmk of any issues!

**Comment by a-l-e-x-d-s-9** [comment]
Thank you!
