### ISSUE TITLE
Error on start - SD15UNETLoader

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [Scorpinaus/ComfyUI-DiffusersLoader#4]
Traceback (most recent call last):
  File "/home/alexds9/Documents/stable_diffusion/ComfyUI/nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/alexds9/Documents/stable_diffusion/ComfyUI/custom_nodes/ComfyUI-DiffusersLoader/__init__.py", line 1, in <module>
    from .sd15_unet_loader import SD15UNETLoader
ModuleNotFoundError: No module named 'ComfyUI-DiffusersLoader.sd15_unet_loader'

Cannot import /home/alexds9/Documents/stable_diffusion/ComfyUI/custom_nodes/ComfyUI-DiffusersLoader module for custom nodes: No module named 'ComfyUI-DiffusersLoader.sd15_unet_loader'

**Comment by Scorpinaus** [comment]
Hi alex, it should be fixed now with the latest commit. Please update via comfyUI manager. Thanks!

**Comment by Scorpinaus** [comment]
Hi alex, is it working for your usecase?

**Comment by a-l-e-x-d-s-9** [comment]
There is no error anymore, but I don't see a way to load a single transformers safetensors file with the extension.

**Comment by a-l-e-x-d-s-9** [comment]
I can load it with UnetLoader.

**Comment by Scorpinaus** [comment]
Hi Alex, can I understand what what is your use case? I will be updating
the individual diffusers loaders so that you'll be able to load individual
components straight from diffusers folders within these few days.

**Comment by a-l-e-x-d-s-9** [comment]
I have been finetuning SD3, the result of the training is a single safetensors file for DiT - safetensors file inside transformer folder in the diffusers format.
Currently, I can load the results from training with UnetLoader node, so it's fine by me.
