### ISSUE TITLE
Interested in merging AuraFlow changes?

### ISSUE THREAD

**Issue by OmegaLambda1998** [Scorpinaus/ComfyUI-DiffusersLoader#5]
Hi, I've forked your repo (https://github.com/OmegaLambda1998/ComfyUI-DiffusersLoader?tab=readme-ov-file) and modified it to allow loading the various AuraFlow fp16 diffuser files (see https://civitai.com/articles/6364/auraflow-fp16-diy-checkpoint-with-comfyui). I reorganised the structure a bit as well, moving a lot of the helper functions used by each node into a shared utils.py. Because of the structural changes, I wanted to give you a chance to review the differences before making a pull request, in case you prefer a different structural setup.

**Comment by Scorpinaus** [comment]
Hi OmegaLamdha1998,

Sure, let me take a look to review the differences.

Regards

**Comment by Scorpinaus** [comment]
Hi @OmegaLambda1998 , some updates. I'll be adding support for AuraFlow diffuser file formats within the next 2 days. I'm doing the testing for it and optimizing some stuff, so do stay tuned! 

Regards

**Comment by Scorpinaus** [comment]
Hi @OmegaLambda1998 I've reviewed your repo! Have made some changes and on the latest commit it supports Auraflow checkpoints in diffusers format! Please test and download the latest commit!

Thank you again for the feedback!

**Comment by OmegaLambda1998** [comment]
Just checked it out, looks awesome!

**Comment by Scorpinaus** [comment]
So can we consider this issue solved? I'll be closing this
