### ISSUE TITLE
extra_model_paths ignored?

### ISSUE THREAD

**Issue by ashllay** [Scorpinaus/ComfyUI-DiffusersLoader#7]
I have models in another disk configured the path in "extra_model_paths.yaml" it shows up on the default comfy DiffusersLoader but it won't show up on Combined DiffusersLoader or any other node from DiffusersLoader custom nodes, it only shows up if i place the model folder on the models/diffusers folder of comfy install dir.

**Comment by Scorpinaus** [comment]
Hi Ashllay, thank you for the feedback. Can you send me an example of how you organized your configuration in the extra_model_paths.yaml file?

**Comment by ashllay** [comment]
> Hi Ashllay, thank you for the feedback. Can you send me an example of how you organized your configuration in the extra_model_paths.yaml file?

full config.
#Rename this to extra_model_paths.yaml and ComfyUI will load it
#config for a1111 ui
#all you have to do is change the base_path to where yours is installed
a111:
    base_path: D:/diffusion/stable-diffusion-webui/
    checkpoints: models/Stable-diffusion
    configs: models/Stable-diffusion
    vae: models/VAE
    loras: |
         models/Lora
         models/LyCORIS
    upscale_models: |
                  models/ESRGAN
                  models/RealESRGAN
                  models/SwinIR
    embeddings: embeddings
    hypernetworks: models/hypernetworks
    controlnet: models/ControlNet
other_ui:
     base_path: G:/diffusion/
     checkpoints: models/checkpoints/
     clip: models/clip/
     clip_vision: models/clip_vision/
     configs: models/configs/
     controlnet: models/controlnet/
     embeddings: models/embeddings/
     loras: models/loras/
     vae: models/vae/
     ipdapter: models/ipdapter/
     diffusers: models/diffusers/
other_ui3:
     base_path: H:/sd/
     checkpoints: models/checkpoints/
     clip: models/clip/
     clip_vision: models/clip_vision/
     configs: models/configs/
     controlnet: models/controlnet/
     embeddings: models/embeddings/
     loras: models/loras/
     upscale_models: models/upscale_models/
     vae: models/vae/
     ipdapter: models/ipdapter/
     unet: models/unet/
     aura-sr: models/aura-sr
     diffusers: models/diffusers/
comfyui:
     base_path: path/to/comfyui/
     checkpoints: models/checkpoints/
     clip: models/clip/
     clip_vision: models/clip_vision/
     configs: models/configs/
     controlnet: models/controlnet/
     embeddings: models/embeddings/
     loras: models/loras/
     upscale_models: models/upscale_models/
     vae: models/vae/
     ipdapter: models/ipdapter/

**Comment by Scorpinaus** [comment]
Hi ashllay, I pushed a recent PR to try to support the extra_model_paths. Please check the latest version and see if it works?

**Comment by ashllay** [comment]
> Hi ashllay, I pushed a recent PR to try to support the extra_model_paths. Please check the latest version and see if it works?

Yes it's working fine now. Thanks!

**Comment by Scorpinaus** [comment]
That's good! Let's close this issue
