### ISSUE TITLE
Model name not show on node 

### ISSUE THREAD

**Issue by wardensc2** [Scorpinaus/ComfyUI-DiffusersLoader#9]
Hi @Scorpinaus 

I try to use your combine Combined Diffusers Loader

But so far I can make your node recognize my model folder inside diffuser folder of ComfyUI

![image](https://github.com/user-attachments/assets/3dba664b-694a-4cc2-a972-a7d8fa5132db)

![image](https://github.com/user-attachments/assets/db094d3e-cfb2-488a-a1ea-341acd7b915e)

![image](https://github.com/user-attachments/assets/81ae5d7b-03c9-45de-b776-471f705af01f)

Can you support me

**Comment by Scorpinaus** [comment]
Hi @wardensc2,

Thank you for asking. I see that your model folder only has the diffusion_pytorch_model safetensors broken into 3 different sub-files. Are you using your own transformer and vae file?

Additionally I don't see that you have a model_index.json file? 

The implementation method for finding model file requires the presence of a model_index.json file, as seen in the picture below: 
<img width="872" alt="image" src="https://github.com/user-attachments/assets/c0fe27bd-cdbe-42df-9d76-6dd83f6363bd">

**Comment by wardensc2** [comment]
> Hi @wardensc2,
> 
> Thank you for asking. I see that your model folder only has the diffusion_pytorch_model safetensors broken into 3 different sub-files. Are you using your own transformer and vae file?
> 
> Additionally I don't see that you have a model_index.json file?
> 
> The implementation method for finding model file requires the presence of a model_index.json file, as seen in the picture below: <img alt="image" width="872" src="https://private-user-images.githubusercontent.com/85672737/393526275-c0fe27bd-cdbe-42df-9d76-6dd83f6363bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMDQwNjQsIm5iZiI6MTczNDIwMzc2NCwicGF0aCI6Ii84NTY3MjczNy8zOTM1MjYyNzUtYzBmZTI3YmQtY2RiZS00MmRmLTlkNzYtNmRkODNmNjM2M2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDE5MTYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZjAwNzk2YzgxZTAzZGNlYmM4NThlYzdhNjI5NjMxYjg5ZjNiNGU3MTZkODYxNWQ4YmYzNzFiNWQyMDkwYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KBSpkRsnl-vama5aOpFCQvXhhXU3Fu4NpBFKiJQy0MM">

Thank you, I will try to do again
